replicaCount: 1

resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 200m
    memory: 256Mi

failurePolicy: Ignore

image:
  repository: infisical/infisical-agent-injector
  tag: v0.1.3

# If need be, you can run the Agent Injector itself on Windows nodes if your cluster supports it.
# This is achieved by setting the nodeSelector to kubernetes.io/os: windows.

# Example:
# nodeSelector:
#   kubernetes.io/os: windows
